FROM tomcat:9.0-jdk17
RUN rm -rf /usr/local/tomcat/webapps/*
COPY target/emaillist.war /usr/local/tomcat/webapps/ROOT.war
ENV PORT=8080
RUN sed -i 's/port="8080"/port="${PORT}"/' /usr/local/tomcat/conf/server.xml
EXPOSE $PORT
CMD ["catalina.sh", "run"]
